HOST: http://api.7digital.com/2.0

--- Inbox API v2.0 ---

--
Inbox Queries
--
list tracks purchased tracks in a users inbox
GET /userinbox/1/items/?page=0&pageSize=10&category=streamable&label=from%20grandma&search=blahblehblih
< 200
< Content-Type: application/xml
<response status="ok">
    <pageInfo>
        <pageNumber>0</pageNumber>
        <pageSize>5</pageSize>
        <total>654216546</total>
    </pageInfo>
    <items>
        <item id="3983">
            <title>It Was...</title>
            <type>track</type>
            <categories>
                <category>free</category>
                <category>streamable</category>
                <category>downloadable</category>
                <category>matched</category>
            </categories>
            <labels>
                <label>this rocks</label>
                <label>from grandma</label>
            </labels>
            <by id="132">
                <name>Lemon Jelly</name>
            </by>
            <bundle id="39874">
                <title>‘64-’95</title>
                <type>Album</type>
            </bundle>
            <image>http://cdn.7static.com/static/img/sleeveart/00/000/373/0000037397_50.jpg</image>
            <track id="3084393">
                <url>http://www.7digital.com/artists/lemon-jelly/64-95/01-It-Was-</url>
            </track>
            <delivery>
                <stream>
                    <url>http://stream.blaaa.s.y.z</url>
                </stream>
                <download remaining="30">
                    <url>http://download.blaaa</url>
                </download>
            </delivery>
        </item>
        <item id="3983">
            <type>ebook</type>
            <title>Harry Potter IV</title>
            <categories>
                <category>free</category>
                <category>ebook</category>
                <category>downloadable</category>
            </categories>
            <labels>
                <label>this ro7digitalcks</label>
                <label>from grandma</label>
            </labels>
            <title>It Was...</title>
            <by id="132">
                <name>J. K. Rowling</name>
            </by>
            <bundle id="39874">
                <title>Harry Potter Collection</title>
            </bundle>
            <image>http://cdn.7static.com/static/img/sleeveart/00/000/373/0000037397_50.jpg</image>
            <ebook id="3084393">
                <url>http://www.7digital.com/artists/college/a-real-hero-ep/01-A-Real-Hero</url>
            </ebook>
            <delivery>
                <download>
                    <url>http://stream.blaaa.s.y.z</url>
                </download>
            </delivery>
        </item>
        <item id="3983">
            <type>track</type>
            <title>User genereated title</title>
            <categories>
                <category>upload</category>
                <category>streamable</category>
            </categories>
            <by id="24332">
                <name>The Garage Band</name>
            </by>
            <bundle id="697091">
                <title>My Garage Hits</title>
            </bundle>
            <delivery>
                <stream>
                    <url>http://stream.blaaa.s.y.z</url>
                </stream>
            </delivery>
        </item>
    </items>
</response>


--
create entry in user inbox
--
POST /userinbox/1/items
<items>
    <source>
        <type>purchase</type>
        <purchase>
            <date>2010-01-11T00:00:00Z</date>
        </purchase>
    </source>
    <item>
        <title>A Real Hero</title>
        <image>http://cdn.7static.com/static/img/sleeveart/00/006/970/0000697091_50.jpg</image>
        <url>http://www.7digital.com/artists/college/a-real-hero-ep/01-A-Real-Hero</url>
        <by id="1257507">
            <name>College &amp; Electric Youth</na
        </by>
        <bundle id="697091">
            <title>A Real Hero EP</title>
            <type>Album</type>
        </bundle>
        <track id="494857">
            <url>http://www.7digital.com/artists/lemon-jelly/64-95/01-It-Was-</url>
        </track>
        <delivery>
            <stream>
                <url>http://stream.blaaa.s.y.z</url>
            </stream>
        </delivery>
    </item>
</items>
<items>
    <source>
        <type>match</type>
        <match>
            <method>tag</method>
            <date>2010-01-11T00:00:00Z</date>
        </match>
    </source>
    <item>
        <title>A Real Hero</title>
        <image>http://cdn.7static.com/static/img/sleeveart/00/006/970/0000697091_50.jpg</image>
        <url>http://www.7digital.com/artists/college/a-real-hero-ep/01-A-Real-Hero</url>
        <by id="1257507">
            <name>College & Electric Youth</name>
        </by>
        <bundle id="697091">
            <title>A Real Hero EP</title>
            <type>Album</type>
        </bundle>
        <track id="3084393">
            <url>http://www.7digital.com/artists/lemon-jelly/64-95/01-It-Was-</url>
        </track>
        <delivery>
            <stream>
                <url>http://stream.blaaa.s.y.z</url>
            </stream>
        </delivery>
    </item>
</items>
< 200
< Content-Type: application/xml
<items>
    <item id="3983">
        <categories>
            <category>shared</category>
            <category>purchase</category>
        </categories>
        <title>A Real Hero</title>
        <url>http://www.7digital.com/artists/college/a-real-hero-ep/01-A-Real-Hero</url>
        <by id="1257507">
            <name>College & Electric Youth</name>
        </by>
        <bundle id="697091">
            <title>A Real Hero EP</title>
            <type>Album</type>
        </bundle>
        <track id="3084393">
            <url>http://www.7digital.com/artists/lemon-jelly/64-95/01-It-Was-</url>
        </track>
        <delivery>
            <stream>
                <url>http://stream.blaaa.s.y.z</url>
            </stream>
        </delivery>
    </item>
</items>

(In case of an uploaded track, the input won't have attribs "sdid":)

(upload track:)
<tracks>
    <track inboxId="3983">
        <categories>
            <category>upload</category>
        </categories>
        <title>User genereated title</title>
        <trackNumber>1</trackNumber>
        <duration>268</duration>
        <artist inboxId="24332">
            <name>The Garage Band</name>
        </artist>
        <release inboxId="697091">
            <title>My Garage Hits</title>
        </release>
        <delivery>
            <stream>
                <url>http://stream.blaaa.s.y.z</url>
            </stream>
        </delivery>
    </track>
</tracks>

=========================================================================== CATEGORIES =====================================================================================
--
list categories & labels in a users inbox
GET /userinbox/1/groups
< 200
< Content-Type: application/xml
<response status="ok">
    <categories>
        <category id="4">
            <name>uploaded</name>
        </category>
        <category id="1">
            <name>purchased</name>
        </category>
        <category id="3">
            <name>matched</name>
        </category>
        <category id="2">
            <name>free</name>
        </category>
    </categories>
    <labels>
        <label id="203">
            <name>this rocks</name>
        </label>
        <label id="4949">
            <name>granny's</name>
        </label>
    </labels>
</response>


====================================================================================== SCAN&MATCH API ===================================================================================================
send match to a users inbox
--
POST /userinbox/1/trackMatch
<matchSubmission type="fingerprint">32rjfiojoi3448rfj3dn398jd9jd</matchSubmission>
<matchSubmission type="tag">
    <track>
        <title>It Was...</title>
        <trackNumber>1</trackNumber>
        <duration>23</duration>
        <artist>
            <name>Lemon Jelly</name>
            <appearsAs>Lemon Jelly</appearsAs>
        </artist>
        <release>
            <title>‘64-’95</title>
        </release>
    </track>
</matchSubmission>
< 200
< Content-Type: application/xml
<matchResult success="true">
    <nextAction>
        <type method="fingerprint">match</type>
    </nextAction>
</matchResult>
<matchResult success="false">
    <nextAction>
        <type method="tag">match</type>
    </nextAction>
</matchResult>
<matchResult success="false">
    <nextAction>
        <type>upload</type>
    </nextAction>
</matchResult>

